name: Hello World
author: Branden miller
description: Say hello to the user

inputs:
  who-to-greet:
    description: Who to greet
    required: true
    default: Branden

outputs:
  time:
    description: The greeting time

runs:
  using: docker
  image: Dockerfile
  # entrypoint:
  args:
    - ${{ inputs.who-to-greet }}
